### ISSUE TITLE
BUG/Security Issue - Password Returned if Password add to query

### ISSUE THREAD

**Issue by TheSecEng** [mattdamon108/go-graphql-api-boilerplate#9]
In its current state, the password will be returned if the password field is added to the query, this is considered a security issue and should not be the case.

Passwords should never be return, encrypted or clear-text.

**Comment by TheSecEng** [comment]
https://github.com/mattdamon108/go-graphql-api-boilerplate/pull/10

**Comment by mattdamon108** [comment]
Totally agreed. Thank you for your PR!
